### ISSUE TITLE
qt: bookmark removal crashes the program

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1997]
**Describe the bug**
qt: bookmark removal crashes the program

**Comment by 375gnu** [comment]
#0  0x0000555555593a22 in BookmarkTreeModel::parent(QModelIndex const&) const ()
#1  0x00007ffff778bb42 in QTreeView::isIndexHidden(QModelIndex const&) const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff77296f0 in QAbstractItemView::rowsAboutToBeRemoved(QModelIndex const&, int, int) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff779652a in QTreeView::rowsAboutToBeRemoved(QModelIndex const&, int, int) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff772593a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff61c4525 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6130aee in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff6137a4b in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x0000555555593c99 in BookmarkTreeModel::removeItem(BookmarkItem*) ()

**Comment by ajtribick** [comment]
Can't reproduce this, on my system removing bookmarks works fine.

**Comment by 375gnu** [comment]
I also cannot reproduce it Qt 6. It happens on Ubuntu 18.04 with Qt 5.

**Comment by ajtribick** [comment]
Works on Qt 5.15 in Ubuntu 23.10. What version of Qt5 is in Ubuntu 18.04?

**Comment by ajtribick** [comment]
I don't think a crash in an out-of-support version of Qt on an out-of-support version of Ubuntu should count as a release blocker.

**Comment by JohnVV** [comment]
this seams to be fixed in the current qt6 linux build ( well as of last months git pull ) 

it WAS , removing the LAST bookmark crashed celestia 
the ones before it could be removed
